### ISSUE TITLE
[Fix] main branch 소스코드 정리

### ISSUE THREAD

**Issue by sunnyineverywhere** [KUBER-LOUDY/kuber-loudy-spring-boot#12]
## Detail
- [x] 메인에 있는 `spring 폴더`, `src 폴더`를 구조에 알맞게 정리
- [ ] `feature/iam`, `feature/member` 브랜치 삭제
- [ ] 브랜치 재분기

**Comment by sunnyineverywhere** [comment]
## 위의 작업 전에 마무리 해야 할 사항
- [x] iam sdk를 api 형태로 바꾸기
- [x] 실행 가능 여부 확인 후 PR

**Comment by yhjune** [comment]
7시 반 넘어서부터 작업하겠습니다

**Comment by yhjune** [comment]
- [IAM client doc](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/using.html)
- [IAM ListAllUser code reference](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/iam/src/main/java/com/example/iam/ListUsers.java#L43)

- 멀티모듈 build.gradle 질문: dependency 주입 안되는 문제

**Comment by yhjune** [comment]
2023.07.26
멀티모듈 변경 : 전체 PR 후 작업 진행

다음 작업
- [x] IAM 데이터 저장
- [x] IAM 확인 과정
- [x] IAM 컨피그 파일 생성 과정 위키 #7
